#!/usr/bin/env python3
"""
NLP-based contextual validation of the Legislation Readiness Index.

This script uses an LLM (Claude via the Anthropic API) to contextually score
legislation texts on the same 6 dimensions as the keyword-based index, providing
independent validation that keyword-based scoring captures meaningful legal
provisions.

METHODOLOGY:
  1. For each country, select the highest-scoring legislation document
  2. Extract the first ~4000 characters (key provisions are typically early)
  3. Send to Claude with a structured scoring rubric
  4. Compare LLM scores with keyword scores (Pearson correlation)

REQUIREMENTS:
  pip install anthropic pdfplumber
  export ANTHROPIC_API_KEY="your-key-here"

OUTPUT:
  data/03_external/legislation/nlp_validation_scores.csv
  outputs/latest/nlp_keyword_validation.csv

NOTE: The NLP scores in the published analysis were generated by Claude Opus 4.6
during the analysis session. This script reproduces the methodology using the
Claude API for independent verification.
"""

import os
import csv
import json
import sys
import time

try:
    import anthropic
except ImportError:
    print("ERROR: anthropic package required. Install with: pip install anthropic")
    print("Then set ANTHROPIC_API_KEY environment variable.")
    sys.exit(1)

try:
    import pdfplumber
except ImportError:
    print("ERROR: pdfplumber required. Install with: pip install pdfplumber")
    sys.exit(1)

ROOT_DIR = "/Volumes/bacdrive/Dropbox/Work/technology_for_IUU_monitoring"
TEXT_DIR = os.path.join(ROOT_DIR, "data/03_external/legislation/texts")
OUTPUT_DIR = os.path.join(ROOT_DIR, "data/03_external/legislation")
RESULTS_DIR = os.path.join(ROOT_DIR, "outputs/latest")

COUNTRIES = {
    "AUS": "Australia", "CAN": "Canada", "CHL": "Chile", "ECU": "Ecuador",
    "GAB": "Gabon", "GRC": "Greece", "IDN": "Indonesia", "ITA": "Italy",
    "MYS": "Malaysia", "MEX": "Mexico", "NZL": "New Zealand", "PAN": "Panama",
    "MDV": "Republic of Maldives", "ZAF": "South Africa", "ESP": "Spain",
}

SCORING_PROMPT = """You are a legal expert assessing fisheries legislation for prosecution readiness.

Score this legislation text on 6 dimensions. Be rigorous — only give high scores when provisions are EXPLICITLY stated in the text. A vague reference to "electronic means" scores lower than an explicit VMS mandate.

DIMENSIONS (score each 0 to max):
1. evidence_admissibility (max 20): Does the law explicitly accept satellite, electronic, VMS, AIS, or technology-derived evidence? Explicit admissibility provisions?
2. penalty_framework (max 20): Are penalties for fisheries/marine violations clearly specified? Explicit fines, imprisonment terms, forfeiture provisions?
3. enforcement_authority (max 15): Are enforcement powers clearly defined? Can officers board vessels, seize gear, arrest violators? Coast guard/navy empowered?
4. technology_provisions (max 20): Does the law mandate VMS, AIS, satellite tracking, electronic logbooks? Specific technology requirements for vessels?
5. liability_framework (max 15): Is liability for vessel owners/operators/masters clearly established? Joint/strict/vicarious liability?
6. legislative_currency (max 10): How current? (2020+ = 10, 2015-2020 = 8, 2010-2015 = 6, 2000-2010 = 4, pre-2000 = 2, pre-1980 = 0)

IMPORTANT: If this document is NOT actually fisheries/marine legislation (e.g., it's a wildlife regulation, environmental code, industrial law, or bilateral treaty), score the fisheries-relevant dimensions as 0 and note this in your justification.

Respond ONLY with valid JSON in this exact format:
{
  "evidence_admissibility": <int>,
  "penalty_framework": <int>,
  "enforcement_authority": <int>,
  "technology_provisions": <int>,
  "liability_framework": <int>,
  "legislative_currency": <int>,
  "total_score": <int>,
  "is_fisheries_relevant": <bool>,
  "brief_justification": "<one paragraph>"
}

LEGISLATION TEXT:
"""


def extract_text(filepath, max_chars=4000):
    """Extract text from PDF or TXT file."""
    if filepath.endswith(".txt"):
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()[:max_chars]

    try:
        text = []
        with pdfplumber.open(filepath) as pdf:
            for page in pdf.pages[:10]:
                page_text = page.extract_text()
                if page_text:
                    text.append(page_text)
                if sum(len(t) for t in text) >= max_chars:
                    break
        return "\n".join(text)[:max_chars]
    except Exception as e:
        return f"[ERROR: {e}]"


def score_with_llm(client, text, model="claude-sonnet-4-20250514"):
    """Score a legislation text using Claude."""
    response = client.messages.create(
        model=model,
        max_tokens=1024,
        messages=[{
            "role": "user",
            "content": SCORING_PROMPT + text
        }]
    )

    # Parse JSON from response
    response_text = response.content[0].text.strip()
    # Handle markdown code blocks
    if response_text.startswith("```"):
        response_text = response_text.split("```")[1]
        if response_text.startswith("json"):
            response_text = response_text[4:]
    return json.loads(response_text)


def main():
    print("=" * 70)
    print("NLP VALIDATION OF LEGISLATION READINESS INDEX")
    print("=" * 70)

    # Check API key
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: Set ANTHROPIC_API_KEY environment variable")
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)

    # Load keyword scores to find top document per country
    kw_scores_path = os.path.join(OUTPUT_DIR, "legislation_readiness_scores.csv")
    with open(kw_scores_path) as f:
        all_docs = list(csv.DictReader(f))

    # Select top-scoring document per country
    from collections import defaultdict
    by_country = defaultdict(list)
    for d in all_docs:
        by_country[d["iso3"]].append(d)

    results = []
    for iso3 in sorted(COUNTRIES):
        docs = by_country.get(iso3, [])
        if not docs:
            print(f"  {COUNTRIES[iso3]:25s} | No documents")
            continue

        # Pick highest-scoring document
        best = max(docs, key=lambda x: float(x["total_score"]))
        filename = best["filename"]

        # Check for English translation
        base = filename.replace(".pdf", "")
        en_path = os.path.join(TEXT_DIR, f"{base}_EN.txt")
        if os.path.exists(en_path):
            filepath = en_path
        else:
            filepath = os.path.join(TEXT_DIR, filename)

        print(f"  {COUNTRIES[iso3]:25s} | {filename}...", end=" ", flush=True)

        text = extract_text(filepath)
        if text.startswith("[ERROR"):
            print(f"FAILED: {text[:60]}")
            continue

        try:
            scores = score_with_llm(client, text)
            total = scores.get("total_score", sum(
                scores.get(d, 0) for d in [
                    "evidence_admissibility", "penalty_framework",
                    "enforcement_authority", "technology_provisions",
                    "liability_framework", "legislative_currency"
                ]
            ))
            print(f"Score: {total}/100")

            results.append({
                "iso3": iso3,
                "country": COUNTRIES[iso3],
                "filename": filename,
                **scores,
            })
        except Exception as e:
            print(f"ERROR: {e}")

        time.sleep(1)  # Rate limiting

    # Save results
    nlp_path = os.path.join(OUTPUT_DIR, "nlp_validation_scores.csv")
    if results:
        fields = list(results[0].keys())
        with open(nlp_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
            writer.writeheader()
            writer.writerows(results)
        print(f"\nSaved NLP scores: {nlp_path}")

    # Compare with keyword scores
    kw_country = {}
    kw_country_path = os.path.join(RESULTS_DIR, "legislation_readiness_index.csv")
    with open(kw_country_path) as f:
        for row in csv.DictReader(f):
            kw_country[row["iso3"]] = float(row["total_score"])

    print(f"\n{'Country':25s} | {'Keyword':>8s} | {'NLP':>8s} | {'Diff':>8s}")
    print("-" * 55)
    kw_vals, nlp_vals = [], []
    for r in results:
        kw = kw_country.get(r["iso3"], 0)
        nlp = r["total_score"]
        kw_vals.append(kw)
        nlp_vals.append(nlp)
        print(f"  {r['country']:23s} | {kw:7.1f} | {nlp:7.1f} | {nlp - kw:+7.1f}")

    # Pearson correlation
    import math
    n = len(kw_vals)
    if n > 2:
        mean_kw = sum(kw_vals) / n
        mean_nlp = sum(nlp_vals) / n
        cov = sum((kw_vals[i] - mean_kw) * (nlp_vals[i] - mean_nlp) for i in range(n)) / n
        std_kw = math.sqrt(sum((x - mean_kw) ** 2 for x in kw_vals) / n)
        std_nlp = math.sqrt(sum((x - mean_nlp) ** 2 for x in nlp_vals) / n)
        r = cov / (std_kw * std_nlp) if std_kw * std_nlp > 0 else 0
        print(f"\nPearson r = {r:.3f} (n={n})")


if __name__ == "__main__":
    main()
